# Generated by Django 6.0.6 on 2026-06-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='gigs.gig'),
        ),
    ]
