# Generated by Django 6.0.6 on 2026-06-14 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_gig'),
        ('gigs', '0001_initial'),
        ('profiles', '0002_alter_talentmedia_options_talentmedia_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status', 'event_date'], name='bookings_bo_client__a95e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['talent', 'status', 'event_date'], name='bookings_bo_talent__bed70a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['gig'], name='bookings_bo_gig_id_496ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['booking', 'status'], name='bookings_di_booking_e0666e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['raised_by', 'status'], name='bookings_di_raised__32752a_idx'),
        ),
    ]
