# Generated by Django 6.0.6 on 2026-07-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_client__a95e3f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.CharField(choices=[('none', 'None'), ('client_free_cancellation', 'Client Free Cancellation'), ('client_late_cancellation', 'Client Late Cancellation'), ('client_no_show', 'Client No Show'), ('talent_cancelled', 'Talent Cancelled'), ('talent_no_show', 'Talent No Show'), ('admin_decision', 'Admin Decision')], default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_confirmation_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show_party',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('talent', 'Talent')], max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_booking_no_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_policy_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='talent_compensation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
