# Generated by Django 6.0.6 on 2026-06-14 22:29

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentmedia',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.profiles.models.talent_media_upload_to),
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='storage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='talentavailability',
            index=models.Index(fields=['talent_profile', 'start_at', 'end_at'], name='profiles_ta_talent__e48be8_idx'),
        ),
        migrations.AddIndex(
            model_name='talentavailability',
            index=models.Index(fields=['availability_type'], name='profiles_ta_availab_fd17b4_idx'),
        ),
        migrations.AddIndex(
            model_name='talentmedia',
            index=models.Index(fields=['talent_profile', 'visibility', 'sort_order'], name='profiles_ta_talent__1bfebf_idx'),
        ),
        migrations.AddIndex(
            model_name='talentmedia',
            index=models.Index(fields=['processing_status'], name='profiles_ta_process_7aecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=models.Index(fields=['primary_category', 'is_featured'], name='profiles_ta_primary_a4ea79_idx'),
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=models.Index(fields=['average_rating', 'reliability_score'], name='profiles_ta_average_52f33c_idx'),
        ),
        migrations.AddIndex(
            model_name='talentprofile',
            index=models.Index(fields=['created_at'], name='profiles_ta_created_b1ff25_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['city', 'region', 'country'], name='profiles_us_city_18dcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['display_name'], name='profiles_us_display_f770d3_idx'),
        ),
    ]
