# Generated by Django 6.0.6 on 2026-06-13 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('verified_only', 'Verified Only')], default='public', max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('is_urgent', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='profiles.eventtype')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GigInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('proposed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('shortlisted', 'Shortlisted'), ('invited', 'Invited'), ('declined', 'Declined')], default='interested', max_length=20)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='gigs.gig')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_interests', to=settings.AUTH_USER_MODEL)),
                ('talent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_interests', to='profiles.talentprofile')),
            ],
            options={
                'unique_together': {('gig', 'talent')},
            },
        ),
        migrations.CreateModel(
            name='GigTalentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_requirements', to='profiles.talentcategory')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_categories', to='gigs.gig')),
            ],
            options={
                'unique_together': {('gig', 'category')},
            },
        ),
    ]
