# Generated by Django 6.0.6 on 2026-07-19 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_balance_due_at_booking_cancellation_policy_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('reason', models.CharField(choices=[('client_free_cancellation', 'Client Free Cancellation'), ('talent_cancelled', 'Talent Cancelled'), ('talent_no_show', 'Talent No Show'), ('balance_overpayment', 'Balance Overpayment'), ('admin_decision', 'Admin Decision')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='fund_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('release_pending', 'Release Pending'), ('released', 'Released'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payout',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payout',
            name='trigger_reason',
            field=models.CharField(choices=[('completion_release', 'Completion Release'), ('late_cancellation_compensation', 'Late Cancellation Compensation'), ('client_no_show_compensation', 'Client No Show Compensation'), ('admin_release', 'Admin Release')], default='completion_release', max_length=40),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status', 'fund_state'], name='payments_pa_booking_88ba1c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'status'], name='payments_pa_payer_i_ebdbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_44281d_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_76e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payee', 'status'], name='payments_pa_payee_i_a1c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['trigger_reason'], name='payments_pa_trigger_3fa2a8_idx'),
        ),
        migrations.AddField(
            model_name='refund',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='refund',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['booking', 'status'], name='payments_re_booking_0e2e74_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['recipient', 'status'], name='payments_re_recipie_e49c97_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reason'], name='payments_re_reason_7c0398_idx'),
        ),
    ]
